version: '3.3'

services:

    leantime:
        image: leantime/leantime:latest
        container_name: leantime
        ports:
            - "8200:80"
        environment:
            - LEAN_DB_HOST=mysql
            - LEAN_DB_USER=admin
            - LEAN_DB_PASSWORD=p4ssw0rd
            - LEAN_DB_DATABASE=leantime
            - TZ="Europe/Madrid"

    mysql:
        image: mariadb:10.7
        container_name: mariadb_leantime
        expose:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD=p4ssw0rd
            - MYSQL_DATABASE=leantime
            - MYSQL_USER=admin
            - MYSQL_PASSWORD=p4ssw0rd

          